export const LOAD_USERS_LOADING = 'REDUX_THUNK_LOAD_USERS_LOADING';
export const LOAD_USERS_ERROR = 'REDUX_THUNK_LOAD_USERS_ERROR';
export const USER_LOGIN_SUCCESS = 'REDUX_THUNK_LOGIN_SUCCESS';
export const USER_SESSION_SUCCESS = 'REDUX_THUNK_USER_SESSION_SUCCESS';
export const UPDATE_USER_ERROR = 'REDUX_THUNK_UPDATE_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'REDUX_THUNK_UPDATE_USER_SUCCESS';

